version: '3'

services:
  mhd-portal:
    build:
      context: .
      dockerfile: Dockerfile
    image: mhd-portal
    container_name: mhd-portal
    ports:
      - 5000:5000
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: ${HOST}
      VIRTUAL_PORT: 5000
      LETSENCRYPT_HOST: ${HOST}
      LETSENCRYPT_EMAIL: mohamedamal680@gmail.com
networks:
  default:
    external:
      name: nginx-proxy

